apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ad-service
  template:
    metadata:
      labels:
        app: ad-service
    spec:
      containers:
        - name: ad-service
          image: ad-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - name: DB_HOST
              value: "mysql"
            - name: DB_USER
              value: "cloudapp_user"
            - name: DB_PASSWORD
              value: "mypassword"
            - name: DB_NAME
              value: "travel_app_db"
---
apiVersion: v1
kind: Service
metadata:
  name: ad-service
spec:
  selector:
    app: ad-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: LoadBalancer
