apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: gcr.io/htwg-cloudapp-hw/backend-api:latest # PLEASE REPLACE htwg-cloudapp-hw
          name: backend
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: DB_HOST
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "cloudapp_user"
            - name: DB_PASSWORD
              value: "mypassword"
            - name: DB_NAME
              value: "travel_app_db"
            - name: GCP_BUCKET_NAME
              value: "htwg-cloudapp-hw.firebasestorage.app"
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: GEMINI_API_KEY
            - name: GCP_SERVICE_ACCOUNT_JSON
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: GCP_SERVICE_ACCOUNT_JSON
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 256Mi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
