apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-scripts
data:
  init.sql: |
    USE travel_app_db;
    CREATE TABLE IF NOT EXISTS travellers (
        id INT AUTO_INCREMENT PRIMARY KEY,
        email VARCHAR(255) UNIQUE NOT NULL,
        name VARCHAR(255) NOT NULL,
        membership_tier VARCHAR(50) DEFAULT 'Free',
        is_admin BOOLEAN DEFAULT FALSE
    );
    CREATE TABLE IF NOT EXISTS itineraries (
        id INT AUTO_INCREMENT PRIMARY KEY,
        traveller_id INT NOT NULL,
        title VARCHAR(255) NOT NULL,
        destination VARCHAR(255) NOT NULL,
        start_date DATE NOT NULL,
        end_date DATE NOT NULL,
        short_description VARCHAR(80) NOT NULL,
        detail_description TEXT,
        is_private TINYINT DEFAULT 0,
        FOREIGN KEY (traveller_id) REFERENCES travellers(id)
    );
